// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iancodes.rooblog.model;

import com.iancodes.rooblog.model.BlogUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BlogUser_Roo_Configurable {
    
    declare @type: BlogUser: @Configurable;
    
}
